[features]
seeds = false
skip-lint = false
[programs.localnet]
advensum = "2piq3bnT1wuDTNUfQMhuvaV2XUhRQheHCDCA8ASAhHh9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aankor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
